#2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,11 +37,10 @@ jobs:
         run: chmod 777 .git/config
 
       - name: Build with Buildozer
-        uses: ArtemSBulgakov/buildozer-action@v1
-        id: buildozer
-        with:
-          command: buildozer android debug
-          buildozer_version: stable
+        id: build
+        run: |
+          buildozer android debug || (echo "Buildozer build failed"; exit 1)
+          echo "Build completed"
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v2
